"""add article chunk search vector

Revision ID: df2c42a78b48
Revises: fdac899276a2
Create Date: 2026-08-30 16:52:12.762500

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "df2c42a78b48"
down_revision: str | Sequence[str] | None = "fdac899276a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "article_chunks",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('russian'::regconfig, text)", persisted=True),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_article_chunks_search_vector_gin",
        "article_chunks",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_article_chunks_search_vector_gin", table_name="article_chunks", postgresql_using="gin"
    )
    op.drop_column("article_chunks", "search_vector")
    # ### end Alembic commands ###
