"""Corpus-wide re-parse: the safety guard and the actual re-extraction.

Extractors get fixed, but the documents already in the database keep the facts
that were pulled at fetch time. ``reprocess_all`` is what carries a fix into
the stored corpus, so what matters here is that it does reach the data and
that it cannot quietly destroy operator decisions on the way.
"""

from __future__ import annotations

import pytest
from sqlalchemy import select
from sqlalchemy.orm import Session, sessionmaker

from court_monitor.services import (
    ReprocessWouldDiscardDecisions,
    count_all_decided_candidates,
    reprocess_all,
)
from court_monitor.storage.db import make_engine
from court_monitor.storage.orm import (
    Base,
    ExtractedFact,
    MatchCandidate,
    PersonRecord,
    SourceDocument,
)


def _session_for(tmp_path) -> Session:
    engine = make_engine(f"sqlite:///{tmp_path / 'reprocess.db'}")
    Base.metadata.create_all(engine)
    return sessionmaker(bind=engine, expire_on_commit=False, class_=Session, future=True)()


def _add_document(session: Session, *, url: str, text: str) -> SourceDocument:
    doc = SourceDocument(
        url=url,
        source_type="telegram",
        content_hash=url,
        parser_status="parsed",
        text=text,
        title="Приговор",
    )
    session.add(doc)
    session.flush()
    return doc


def _add_stale_fact(session: Session, doc: SourceDocument, value: str) -> ExtractedFact:
    """A fact the current extractor would never produce."""
    fact = ExtractedFact(
        document_id=doc.id,
        entity="person",
        field="full_name_original",
        value=value,
        extraction_method="regex:name:two_tokens",
        confidence=0.6,
    )
    session.add(fact)
    session.flush()
    return fact


def _decide(session: Session, fact: ExtractedFact, status: str) -> None:
    record = PersonRecord(
        source="rfm",
        raw_name="Иванов Иван Иванович",
        search_name="иванов иван иванович",
        normalized_name="иванов иван иванович",
    )
    session.add(record)
    session.flush()
    session.add(
        MatchCandidate(
            extracted_fact_id=fact.id,
            person_record_id=record.id,
            score=0.5,
            algorithm_version="match-v3",
            status=status,
        )
    )
    session.flush()


def test_refuses_when_any_decision_would_be_lost(tmp_path):
    """The check is corpus-wide on purpose: a per-document check would delete
    the facts of every earlier document before reaching the protected one."""
    session = _session_for(tmp_path)
    try:
        safe = _add_document(session, url="https://e.invalid/1", text="Жители Сочи вышли.")
        _add_stale_fact(session, safe, "Жители Сочи")
        protected = _add_document(session, url="https://e.invalid/2", text="Приговор.")
        _decide(session, _add_stale_fact(session, protected, "Иванов Иван"), "confirmed")

        with pytest.raises(ReprocessWouldDiscardDecisions) as exc:
            reprocess_all(session)

        assert exc.value.decided == 1
        assert exc.value.document_id is None
        # nothing touched, including the unprotected document
        assert len(session.execute(select(ExtractedFact)).scalars().all()) == 2
    finally:
        session.close()


def test_pending_candidates_do_not_block(tmp_path):
    """Pending candidates carry no human judgement and are regenerated by the
    next match run — blocking on them would make the command unusable."""
    session = _session_for(tmp_path)
    try:
        doc = _add_document(session, url="https://e.invalid/1", text="Приговор.")
        _decide(session, _add_stale_fact(session, doc, "Иванов Иван"), "pending")

        assert count_all_decided_candidates(session) == 0
        reprocess_all(session)  # must not raise
    finally:
        session.close()


def test_force_overrides_the_guard(tmp_path):
    session = _session_for(tmp_path)
    try:
        doc = _add_document(session, url="https://e.invalid/1", text="Приговор.")
        _decide(session, _add_stale_fact(session, doc, "Иванов Иван"), "rejected")

        stats = reprocess_all(session, force=True)

        assert stats.documents == 1
    finally:
        session.close()


def test_drops_facts_the_current_extractor_no_longer_produces(tmp_path):
    """The whole point of the command: a stored fact that the fixed extractor
    would reject must not survive the pass."""
    session = _session_for(tmp_path)
    try:
        doc = _add_document(
            session,
            url="https://e.invalid/1",
            text="Жители Сочи вышли после приговора Игорю Додонову по ч. 2 ст. 205 УК РФ.",
        )
        _add_stale_fact(session, doc, "Жители Сочи")

        reprocess_all(session)

        names = [
            f.value
            for f in session.execute(select(ExtractedFact)).scalars()
            if f.field == "full_name_original"
        ]
        assert "Жители Сочи" not in names  # collective head, dropped by the fix
        assert "Игорю Додонову" in names  # and the real person is picked up
    finally:
        session.close()


def test_limit_caps_the_pass(tmp_path):
    session = _session_for(tmp_path)
    try:
        for i in range(3):
            _add_document(session, url=f"https://e.invalid/{i}", text="Приговор.")

        stats = reprocess_all(session, limit=2)

        assert stats.documents == 2
    finally:
        session.close()


def test_reports_the_fact_count_delta(tmp_path):
    session = _session_for(tmp_path)
    try:
        doc = _add_document(session, url="https://e.invalid/1", text="Жители Сочи вышли.")
        _add_stale_fact(session, doc, "Жители Сочи")

        stats = reprocess_all(session)

        assert stats.facts_before == 1
        assert stats.facts_after == stats.facts_before + stats.facts_delta
    finally:
        session.close()
